import * as fs from 'node:fs';
import * as path from 'node:path';
/**
 * Core pure functions for generating token-budgeted AI context bundles.
 * Grounded in b4x_context and B4XMcpServer's ContextTools.cs / SkeletonGenerator.cs:
 * Scans project modules, builds ASCII tree, collapses non-focused module bodies into
 * compact signatures, estimates token consumption, and formats an AI-ready Markdown bundle.
 *
 * No VS Code dependencies for clean unit-testing.
 */

export interface SkeletonResult {
  skeleton: string;
  originalLines: number;
  skeletonLines: number;
  omittedSubsCount: number;
}

export interface ProjectFileEntry {
  relPath: string;
  kind: 'bas' | 'b4a' | 'b4j' | 'b4i' | 'bal' | 'bjl' | 'bil' | 'other';
  content?: string;
  isFocused?: boolean;
  focusSub?: string;
}

export interface ContextBundleOptions {
  projectName: string;
  platform?: string;
  projectRoot?: string;
  files: ProjectFileEntry[];
  buildErrors?: string[];
  activeFile?: string;
  activeSub?: string;
  activeLine?: number;
  libraries?: string[];
}

/**
 * Estimates token count based on typical B4X source code density (~4 characters per token).
 */
export function estimateTokens(text: string): number {
  if (!text) return 0;
  return Math.ceil(text.length / 4);
}

/**
 * Transforms a B4X module into a compact skeleton, keeping declarations (Process_Globals,
 * Globals, Class_Globals, Types) and Sub signatures, while omitting routine bodies.
 * If a focusSub is specified, that Sub is kept expanded in full.
 */
export function skeletonizeModule(source: string, focusSub?: string): SkeletonResult {
  const lines = source.split(/\r?\n/);
  const out: string[] = [];

  let inSub = false;
  let currentSubName = '';
  let subBodyLines = 0;
  let omittedSubsCount = 0;

  // Skip IDE header metadata before @EndOfDesignText@
  let startIdx = 0;
  for (let idx = 0; idx < lines.length; idx++) {
    if ((lines[idx] ?? '').includes('@EndOfDesignText@')) {
      startIdx = idx + 1;
      break;
    }
  }

  for (let i = startIdx; i < lines.length; i++) {
    const raw = lines[i] ?? '';
    const trimmed = raw.trim();

    // Check Sub start
    const subMatch = /^(?:Public\s+|Private\s+)?Sub\s+([a-zA-Z0-9_]+)\b/i.exec(trimmed);
    if (subMatch && !inSub) {
      const subName = subMatch[1] ?? '';
      const subNameLower = subName.toLowerCase();

      // Always keep Globals sections in full
      if (subNameLower === 'process_globals' || subNameLower === 'globals' || subNameLower === 'class_globals') {
        out.push(raw);
        continue;
      }

      inSub = true;
      currentSubName = subName;
      subBodyLines = 0;
      out.push(raw);
      continue;
    }

    if (inSub) {
      if (/^End\s+Sub\b/i.test(trimmed)) {
        inSub = false;
        const isFocused = focusSub && currentSubName.toLowerCase() === focusSub.toLowerCase();
        if (!isFocused) {
          if (subBodyLines > 0) {
            out.push(`    ' ... body omitted (${subBodyLines} lines) ...`);
            omittedSubsCount++;
          }
        }
        out.push(raw);
        continue;
      } else {
        subBodyLines++;
        const isFocused = focusSub && currentSubName.toLowerCase() === focusSub.toLowerCase();
        if (isFocused) {
          out.push(raw);
        }
        continue;
      }
    }

    out.push(raw);
  }

  const skeletonText = out.join('\n');
  return {
    skeleton: skeletonText,
    originalLines: lines.length,
    skeletonLines: out.length,
    omittedSubsCount,
  };
}

/**
 * Builds an ASCII visual file tree for project modules and layouts.
 */
export function generateAsciiTree(relPaths: string[]): string {
  const sorted = [...relPaths].sort();
  const lines: string[] = ['.'];

  for (let i = 0; i < sorted.length; i++) {
    const isLast = i === sorted.length - 1;
    const prefix = isLast ? '└── ' : '├── ';
    lines.push(prefix + sorted[i]);
  }

  return lines.join('\n');
}

/**
 * Generates a full Markdown AI context bundle optimized for token efficiency.
 */
export function generateContextBundle(options: ContextBundleOptions): string {
  const sections: string[] = [];

  sections.push(`# B4X Context Bundle: ${options.projectName}`);
  sections.push(`> Generated by B4X IntelliSense (Token-Optimized)`);

  // Build errors (if any)
  if (options.buildErrors && options.buildErrors.length > 0) {
    sections.push(`\n## ⚠️ Recent Compiler Errors`);
    sections.push('```text');
    sections.push(options.buildErrors.join('\n'));
    sections.push('```');
  }

  // Project Structure
  const filePaths = options.files.map((f) => f.relPath);
  sections.push(`\n## Project File Structure`);
  sections.push('```text');
  sections.push(generateAsciiTree(filePaths));
  sections.push('```');

  // File Contents
  sections.push(`\n## Module Contents`);

  let totalOriginalLines = 0;
  let totalOutputLines = 0;

  for (const file of options.files) {
    if (!file.content || isExcludedFromBundle(file.content)) continue;

    const isSourceModule = file.kind === 'bas' || file.kind === 'b4a' || file.kind === 'b4j' || file.kind === 'b4i';
    const isFocusedFile = file.isFocused || (options.activeFile && options.activeFile.endsWith(file.relPath));
    const focusSub = isFocusedFile ? (file.focusSub || options.activeSub) : undefined;

    if (isSourceModule) {
      if (isFocusedFile && !focusSub) {
        // Focused file without specific sub focus: keep entire file
        sections.push(`\n### ${file.relPath} (Full Content - Active File)`);
        sections.push('```b4x');
        sections.push(file.content);
        sections.push('```');
        const linesCount = file.content.split(/\r?\n/).length;
        totalOriginalLines += linesCount;
        totalOutputLines += linesCount;
      } else {
        // Generate skeleton
        const skel = skeletonizeModule(file.content, focusSub);
        const focusNote = focusSub ? ` (Focus Sub: '${focusSub}')` : ' (Skeleton View)';
        sections.push(`\n### ${file.relPath}${focusNote}`);
        sections.push('```b4x');
        sections.push(skel.skeleton);
        sections.push('```');
        totalOriginalLines += skel.originalLines;
        totalOutputLines += skel.skeletonLines;
      }
    } else {
      sections.push(`\n### ${file.relPath}`);
      sections.push('```');
      sections.push(file.content);
      sections.push('```');
      const linesCount = file.content.split(/\r?\n/).length;
      totalOriginalLines += linesCount;
      totalOutputLines += linesCount;
    }
  }

  const bundleText = sections.join('\n');
  const tokenEst = estimateTokens(bundleText);

  // Insert token header stats
  const headerStats = `\n**Token Budget:** ~${tokenEst.toLocaleString()} estimated tokens | Original Lines: ${totalOriginalLines} | Compressed Lines: ${totalOutputLines}\n`;
  sections.splice(2, 0, headerStats);

  return sections.join('\n');
}


/**
 * Automatically redacts sensitive passwords, secrets, and API tokens from code bundles.
 */
export function sanitizeSecrets(content: string): string {
  if (!content) return content;
  return content.replace(
    /((?:['"]?\b(?:api[_-]?key|apikey|secret|password|passwd|auth[_-]?token|access[_-]?token)\b['"]?(?:\s+As\s+\w+)?)\s*[:=]\s*["'])([^"']{4,})(["'])/gi,
    '$1[REDACTED]$3'
  );
}

/**
 * Checks if a module has explicitly excluded itself from code bundles via official attribute.
 */
export function isExcludedFromBundle(content?: string): boolean {
  if (!content) return false;
  return /^\s*(?:'|Rem\s+)?#ExcludeCodeFromBundle\s*:\s*True/im.test(content);
}

/**
 * Generates an official B4X IDE (Erel-compatible) JSON Code Bundle.
 * Mirrors the native Ctrl+R bundle format containing project metadata,
 * libraries, active caret location, and full sanitized module contents.
 */
export function generateJsonContextBundle(options: ContextBundleOptions): string {
  const modulesList: Array<{
    name: string;
    path: string;
    kind: string;
    content: string;
  }> = [];

  const layoutsList: Array<{
    name: string;
    path: string;
  }> = [];

  for (const f of options.files) {
    if (isExcludedFromBundle(f.content)) {
      continue;
    }

    const isLayout = f.kind === 'bal' || f.kind === 'bjl' || f.kind === 'bil';
    const baseName = f.relPath.replace(/^.*[\\/]/, '').replace(/\.[^/.]+$/, '');

    if (isLayout) {
      layoutsList.push({
        name: baseName,
        path: f.relPath,
      });
    } else if (f.content) {
      modulesList.push({
        name: baseName,
        path: f.relPath,
        kind: f.kind,
        content: sanitizeSecrets(f.content),
      });
    }
  }

  const caretModule = options.activeFile
    ? options.activeFile.replace(/^.*[\\/]/, '').replace(/\.[^/.]+$/, '')
    : undefined;

  const bundleObj = {
    project: options.projectName,
    platform: options.platform || 'b4a',
    timestamp: new Date().toISOString(),
    caret: {
      file: options.activeFile,
      module: caretModule,
      sub: options.activeSub,
      line: options.activeLine,
    },
    libraries: options.libraries || [],
    errors: options.buildErrors || [],
    modules: modulesList,
    layouts: layoutsList,
  };

  return JSON.stringify(bundleObj, null, 2);
}

/**
 * Saves generated AI Code Bundle into a CodeBundle folder in the root of the workspace.
 */
export function saveCodeBundleToWorkspace(
  workspaceRoot: string,
  projectName: string,
  format: 'markdown' | 'json',
  content: string
): { outputPath: string; relativePath: string } {
  const bundleFolder = path.join(workspaceRoot, 'CodeBundle');
  if (!fs.existsSync(bundleFolder)) {
    fs.mkdirSync(bundleFolder, { recursive: true });
  }

  const ext = format === 'json' ? '.json' : '.md';
  const fileName = `${projectName}${ext}`;
  const outputPath = path.join(bundleFolder, fileName);
  fs.writeFileSync(outputPath, content, 'utf8');

  return {
    outputPath,
    relativePath: path.join('CodeBundle', fileName).replace(/\\/g, '/'),
  };
}
